language: bash
services: docker

env:
  - VARIANT=fpm
  - VARIANT=apache

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="deskpro:${VARIANT}"
  - hash_before=$(git write-tree)

script:
  # Test Image
  - travis_retry docker build -t "$image" "${VARIANT}"
  - ~/official-images/test/run.sh "$image"

  # Test update.sh
  - ./update.sh
  - bash -c "[[ $hash_before = $(git add -A && git write-tree) ]]"

  # Test requirements
  - docker run -it --rm "$image" bash -c 'unzip -q /usr/src/deskpro.zip ; bin/check_requirements'

after_script:
  - docker images
